# Numpy-Study
`17/07/09` `jskyzero`


## 为什么使用Numpy

一般来说，在Python中我们使用list来保存一组数据，但是对于数值计算来说list保存指针的储存方式这样浪费了内存和CPU。提供的araay模块虽然是直接保存数值的，但是没有对多维和运算函数的支持，Numpy则弥补了这些不足

## 使用Numpy

键入`pip install numpy`来安装，以下示例假定使用如下方式导入NumPy函数库

In [1]:
import random
import numpy as np

print(type(np))

<class 'module'>


### 创建N-dimensional array object

除了下述一些基本创建，还可以使用`np.zeros()`,`np.ones `,`np.empty()`接收shape创建

In [2]:
# 使用list初始化
a = np.array(list(range(1, 10, 2)))
# 使用 arange(begin, end, space), [begin, end) 
b = np.arange(1, 10, 2)
# 使用 linespace(begin, end, nums), [begin, end], 指定元素个数
c = np.linspace(1, 2, 3, endpoint=True)
# 使用 logspace创建等比数列
d = np.logspace(1, 3, 3, base=2, endpoint=True)
# 使用 string
f = np.fromstring("abcdef", dtype=np.int8)
# 使用 func, 第二个参数是shape
g = np.fromfunction(abs, (10, ))

print("a = {}".format(a))
print("b = {}".format(b))
print("c = {}".format(c))
print("d = {}".format(d))
print("f = {}".format(f))
print("g = {}".format(g))

a = [1 3 5 7 9]
b = [1 3 5 7 9]
c = [ 1.   1.5  2. ]
d = [ 2.  4.  8.]
f = [ 97  98  99 100 101 102]
g = [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


### np.array基本属性

字面上的属性就不解释了，学过线性代数的应该都看得懂，要注意可以修改shape来直接改变形状

In [3]:
arr = np.array(range(1, 10))
print('arr\t\t', arr)
print('arr.ndim\t', arr.ndim)
print('arr.shape\t', arr.shape)
print('arr.size\t', arr.size)
print('arr.dtype\t', arr.dtype)

arr		 [1 2 3 4 5 6 7 8 9]
arr.ndim	 1
arr.shape	 (9,)
arr.size	 9
arr.dtype	 int32


### 基本运算

In [4]:
a = np.array([1, 2])
b = np.array([[1], [2]])
print("a + a = {}".format(a + a))
print("a - a = {}".format(a - a))
print("a * 2 = {}".format(a * a))
print("a / 2 = {}".format(a / 2))
print("a * b = {}".format(a * b))
print("a.dot(b) = {}".format(a.dot(b)))
print("np.dot(a, b) = {}".format(np.dot(a, b)))

a + a = [2 4]
a - a = [0 0]
a * 2 = [1 4]
a / 2 = [ 0.5  1. ]
a * b = [[1 2]
 [2 4]]
a.dot(b) = [5]
np.dot(a, b) = [5]


### 基本函数

In [5]:
a = np.logspace(1, 3, 3,  base=3, endpoint=True)
print("a.min() = {}".format(a.min()))
print("a.max() = {}".format(a.max()))
print("a.sum() = {}".format(a.sum()))
print("还有很多基本函数，请参阅NumPy官方参考")

a.min() = 3.0
a.max() = 27.0
a.sum() = 39.0
还有很多基本函数，请参阅NumPy官方参考


### 切片

In [6]:
a = np.arange(10) ** 3
print("a[:] = {}".format(a))
print("a[1:2] = {}".format(a[1:2]))
print("a[-2:-1] = {}".format(a[-2:-1]))
print("a[::2] = {}".format(a[::2]))
print("np.hsplit(a, [3,4]) = {}".format(np.hsplit(a, [3,4])))
print("np.vsplit(a, [1]) = {}".format(np.hsplit(a, [1])))

a[:] = [  0   1   8  27  64 125 216 343 512 729]
a[1:2] = [1]
a[-2:-1] = [512]
a[::2] = [  0   8  64 216 512]
np.hsplit(a, [3,4]) = [array([0, 1, 8], dtype=int32), array([27], dtype=int32), array([ 64, 125, 216, 343, 512, 729], dtype=int32)]
np.vsplit(a, [1]) = [array([0], dtype=int32), array([  1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)]


### statck

In [7]:
a = np.arange(1, 10, 1)
np.vstack((a, a))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
np.hstack((a, a))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a = np.fromfunction(lambda x, y: x + y, (10, 10))
a[1][1] = 3
a

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
       [  1.,   3.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.],
       [  3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.],
       [  4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,  13.],
       [  5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,  13.,  14.],
       [  6.,   7.,   8.,   9.,  10.,  11.,  12.,  13.,  14.,  15.],
       [  7.,   8.,   9.,  10.,  11.,  12.,  13.,  14.,  15.,  16.],
       [  8.,   9.,  10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.],
       [  9.,  10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.]])